spring.application.name=yomira-quiz-service
spring.ai.ollama.base-url=https://ollama.com/api
spring.ai.ollama.api-key=${OLLAMA_API_KEY}
spring.ai.ollama.chat.options.model=gpt-oss:120b-cloud
spring.ai.ollama.chat.options.temperature=0.3
server.port=8082
logging.level.org.springframework.ai=DEBUG
